// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC4l6WYPlM1dDQh5WWQrJ6MsserJUVyjE',
    appId: '1:53184141765:web:53e99baa8b444f6e5613ac',
    messagingSenderId: '53184141765',
    projectId: 'mazad-59a47',
    authDomain: 'mazad-59a47.firebaseapp.com',
    storageBucket: 'mazad-59a47.appspot.com',
    measurementId: 'G-8T215QVVYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATOEwmHPLEvBukYWD7P_lCsXqwP_-RX0A',
    appId: '1:53184141765:android:fa6b65915b75bb0d5613ac',
    messagingSenderId: '53184141765',
    projectId: 'mazad-59a47',
    storageBucket: 'mazad-59a47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVFNOge3c4vd6TQFeF0tPszt889ZNzH9U',
    appId: '1:53184141765:ios:970a8f4da77369a65613ac',
    messagingSenderId: '53184141765',
    projectId: 'mazad-59a47',
    storageBucket: 'mazad-59a47.appspot.com',
    iosBundleId: 'com.example.m19play',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVFNOge3c4vd6TQFeF0tPszt889ZNzH9U',
    appId: '1:53184141765:ios:c7f3c2cd724847da5613ac',
    messagingSenderId: '53184141765',
    projectId: 'mazad-59a47',
    storageBucket: 'mazad-59a47.appspot.com',
    iosBundleId: 'com.example.m19play.RunnerTests',
  );
}
